### ISSUE TITLE
How to Install Audiobookshelf on Centos 7

### ISSUE THREAD

**Issue by drbinkley** [lkiesow/audiobookshelf-rpm#1]
I want to install Audiobookshelf on my hosted virtual private server, but Liquidweb techs are asking for instructions to install it since the Audiobookshelf site does not include Centos 7. What can I tell them? Thanks.

**Comment by lkiesow** [comment]
My real suggestion would be to upgrade to CentOS Stream 9 (or similar) as your base operating system. The end of life for CentOS 7 is only next year, but setting up a new service, you might already want to switch now.

That being said, I didn't build the repository for CentOS 7 since the OS has actually changed a bit between el7 and el8, and I don't really have any infrastructure left to properly test el7 packages. Close before the EOL, I also didn't want to build that up again. But the actual build instruction for el7 should be pretty close. If you want to set that up and test it, feel free to provide a pull request. I don't mind accepting that.

If you don't want to upgrade and not spend any time on adding the el7 build infrastructure, my suggestion would be to get Docker running and use [Audiobookshelf's Docker deployment](https://www.audiobookshelf.org/docs#docker-compose-install) since it is OS-agnostic.
